### ISSUE TITLE
geom_contour

### ISSUE THREAD

**Issue by fipoucat** [thomasp85/ggplot2_workshop#6]
Hi Thomas,
More a question than an issue; In fact I am using ggplot to contour sea level pressure using geom_contour and can plot values without problem. Now I need to plot a specific value (here 1015) as bold or thicker contour than the others and wonder if you see a way to do it?
below the command I use: 
 geom_contour2(data = synclas_gather_df, aes(x=x,y=y,z=value), binwidth = 2, color = "black") +
  scale_fill_gradientn(colours = colorRamps::matlab.like2(100), name = "hPa",breaks=0:5) + 
  scale_colour_gradient(guide = 'none') + facet_wrap(~key, ncol = 4) +

The interval I have here is 2, so I have let's say 1010, 1012, 1014, 1016 etc. Now how to skip the 1014 and replace it with 1015?
Thank you for the noce tutorail

**Comment by thomasp85** [comment]
Hi @fipoucat — such questions are much better asked on [RStudio Community](https://community.rstudio.com) where there are lots of people who can help out 🙂
